name: autocells
description: "Software para automatizar hojas de Excel."
publish_to: 'none'
version: 0.2.2-alpha

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.4.4
  file_picker: ^8.0.0+1
  http: ^1.2.1
  package_info_plus: ^6.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  window_manager: ^0.3.8
  url_launcher: ^6.2.6
  webview_windows: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
